server:
  port: 18085

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 70MB
  application:
    name: t-camp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tongsuo?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: tongsuo
    password: tongsuo@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 50
      max-active: 200
      max-wait: 120000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      filters: stat

springdoc:
  api-docs:
    enabled: true
